vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.tabstop = 8
vim.opt.softtabstop = 0
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.autoindent = true 
vim.opt.smarttab = true
vim.opt.wrap = false
vim.opt.mouse = "a"
vim.opt.completeopt = 'menuone,noinsert,noselect'
vim.opt.errorbells = false 
vim.opt.hlsearch = false
vim.opt.incsearch = true 
vim.opt.cmdheight = 1
vim.opt.updatetime = 50 
vim.opt.shortmess:append("c")
vim.opt.colorcolumn = "80"
vim.api.nvim_set_keymap('i', '<Tab>', 'pumvisible() ? "\\<C-n>" : "\\<Tab>"', {expr = true})
vim.api.nvim_set_keymap('i', '<S-Tab>', 'pumvisible() ? "\\<C-p>" : "\\<Tab>"', {expr = true})
